kind: pipeline
type: kubernetes
name: default
steps:
- name: test
  image: golang:1.10-alpine
  commands:
    - "go test"
- name: build
  image: golang:1.10-alpine
  commands:
    - "go build -o ./myapp"
- name: publish
  image: plugins/docker
  settings:
    registry: harbor.local.unixexpo.com
    repo: harbor.local.unixexpo.com/drone-test/my-app
    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: deliver
  image: sinlead/drone-kubectl
  settings:
    kubernetes_server:
      from_secret: kubernetes_server
    kubernetes_cert:
      from_secret: kubernetes_cert
    kubernetes_token:
      from_secret: kubernetes_token
  commands:
    - kubectl apply -f deployment.yml
    


